name: Primer Workflow
on: push
jobs:
  mi_primer_test:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar pytest
        run: pip install pytest
      - name: Ejecutar codigo
        run: pytest test.py
