name: Primer Workflow
on: push
jobs:
  mi_primer_test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOs-latest]
    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Instalar pytest
        run: pip install pytest
      - name: Ejecutar codigo
        run: pytest test.py
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: uelorriaga/holamundo
