name: Primer Workflow
on:
  push:
    branches: # Ejecutar action si se hace push en ramas concretas, si solo se pone push, se hara para todas las ramas
      - main
jobs:
  mi_primer_test: # Cada tarea tienen una serie de pasos y hay que especificar donde se ejecuta (runs-on)
    runs-on: ${{matrix.os}} # Ejecutar en todos los OS de la lista matrix.os
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOs-latest]
    steps: # Pasos de la tarea mi_primer_test
      - name: Bajar codigo
        uses: actions/checkout@v4 # Clonar el repositorio en el runner (contenedor de ejecucion)
      - name: Instalar pytest
        run: pip install pytest
      - name: Ejecutar codigo
        run: pytest test.py
  
  build_push:
    runs-on: ubuntu-latest
    needs: mi_primer_test
    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4 # Clonar el repositorio en el runner (contenedor de ejecucion)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          #context: /app
          push: true
          tags: unaielorriaga/ci-cd-app
      #- name: Build and push
      #  run: |
      #    cd app/
      #    docker build -t unaielorriaga/ci-cd-app .
      #    docker push unaielorriaga/ci-cd-app
      #    cd ..
